######################################################################
# Automatically generated by qmake (3.0) ?? 5? 21 17:21:40 2023
######################################################################

TEMPLATE = app
TARGET = start1_useqmake
INCLUDEPATH += .

QT += gui widgets

# Input
SOURCES += main.cpp
